// Temperatures/OneWire
TCLo = new Array(^SPTemp0Low^,^SPTemp1Low^,^SPTemp2Low^,^SPTemp3Low^,^SPTemp4Low^);
TDLo = new Array(^Temp0Low^,^Temp1Low^,^Temp2Low^,^Temp3Low^,^Temp4Low^);
TLoB1 = new Array(^Temp0LowB1^,^Temp1LowB1^,^Temp2LowB1^,^Temp3LowB1^,^Temp4LowB1^);
TLoB2 = new Array(^Temp0LowB2^,^Temp1LowB2^,^Temp2LowB2^,^Temp3LowB2^,^Temp4LowB2^);
TLoB3 = new Array(^Temp0LowB3^,^Temp1LowB3^,^Temp2LowB3^,^Temp3LowB3^,^Temp4LowB3^);
TLoB4 = new Array(^Temp0LowB4^,^Temp1LowB4^,^Temp2LowB4^,^Temp3LowB4^,^Temp4LowB4^);
TCHi = new Array(^SPTemp0Hi^,^SPTemp1Hi^,^SPTemp2Hi^,^SPTemp3Hi^,^SPTemp4Hi^);
TDHi = new Array(^Temp0Hi^,^Temp1Hi^,^Temp2Hi^,^Temp3Hi^,^Temp4Hi^);
THiB1 = new Array(^Temp0HiB1^,^Temp1HiB1^,^Temp2HiB1^,^Temp3HiB1^,^Temp4HiB1^);
THiB2 = new Array(^Temp0HiB2^,^Temp1HiB2^,^Temp2HiB2^,^Temp3HiB2^,^Temp4HiB2^);
THiB3 = new Array(^Temp0HiB3^,^Temp1HiB3^,^Temp2HiB3^,^Temp3HiB3^,^Temp4HiB3^);
THiB4 = new Array(^Temp0HiB4^,^Temp1HiB4^,^Temp2HiB4^,^Temp3HiB4^,^Temp4HiB4^);

//Analogue In
AICLo = new Array(^SPAnIn0Low^,^SPAnIn1Low^,^SPAnIn2Low^,^SPAnIn3Low^);
AIDLo = new Array(^AnIn0Low^,^AnIn1Low^,^AnIn2Low^,^AnIn3Low^);
AILoB1 = new Array(^AnIn0LowB1^,^AnIn1LowB1^,^AnIn2LowB1^,^AnIn3LowB1^);
AILoB2 = new Array(^AnIn0LowB2^,^AnIn1LowB2^,^AnIn2LowB2^,^AnIn3LowB2^);
AILoB3 = new Array(^AnIn0LowB3^,^AnIn1LowB3^,^AnIn2LowB3^,^AnIn3LowB3^);
AILoB4 = new Array(^AnIn0LowB4^,^AnIn1LowB4^,^AnIn2LowB4^,^AnIn3LowB4^);
AICHi = new Array(^SPAnIn0Hi^,^SPAnIn1Hi^,^SPAnIn2Hi^,^SPAnIn3Hi^);
AIDHi = new Array(^AnIn0Hi^,^AnIn1Hi^,^AnIn2Hi^,^AnIn3Hi^);
AIHiB1 = new Array(^AnIn0HiB1^,^AnIn1HiB1^,^AnIn2HiB1^,^AnIn3HiB1^);
AIHiB2 = new Array(^AnIn0HiB2^,^AnIn1HiB2^,^AnIn2HiB2^,^AnIn3HiB2^);
AIHiB3 = new Array(^AnIn0HiB3^,^AnIn1HiB3^,^AnIn2HiB3^,^AnIn3HiB3^);
AIHiB4 = new Array(^AnIn0HiB4^,^AnIn1HiB4^,^AnIn2HiB4^,^AnIn3HiB4^);
// End
