//Scenes
ScDM = new Array(^Scene0DigMask^,^Scene1DigMask^,^Scene2DigMask^,^Scene3DigMask^,^Scene4DigMask^,^Scene5DigMask^,^Scene6DigMask^,^Scene7DigMask^,^Scene8DigMask^,^Scene9DigMask^,^Scene10DigMask^,^Scene11DigMask^); 
ScDS = new Array(^Scene0DigState^,^Scene1DigState^,^Scene2DigState^,^Scene3DigState^,^Scene4DigState^,^Scene5DigState^,^Scene6DigState^,^Scene7DigState^,^Scene8DigState^,^Scene9DigState^,^Scene10DigState^,^Scene11DigState^); 
ScAM = new Array(^Scene0AnMask^,^Scene1AnMask^,^Scene2AnMask^,^Scene3AnMask^,^Scene4AnMask^,^Scene5AnMask^,^Scene6AnMask^,^Scene7AnMask^,^Scene8AnMask^,^Scene9AnMask^,^Scene10AnMask^,^Scene11AnMask^); 
ScAS = new Array(^Scene0AnState^,^Scene1AnState^,^Scene2AnState^,^Scene3AnState^,^Scene4AnState^,^Scene5AnState^,^Scene6AnState^,^Scene7AnState^,^Scene8AnState^,^Scene9AnState^,^Scene10AnState^,^Scene11AnState^); 

//Schedules
SchD = new Array(^Sch0Days^,^Sch1Days^,^Sch2Days^,^Sch3Days^,^Sch4Days^,^Sch5Days^,^Sch6Days^,^Sch7Days^,^Sch8Days^,^Sch9Days^,^Sch10Days^,^Sch11Days^,^Sch12Days^,^Sch13Days^,^Sch14Days^,^Sch15Days^); 
SchH = new Array(^Sch0Hours^,^Sch1Hours^,^Sch2Hours^,^Sch3Hours^,^Sch4Hours^,^Sch5Hours^,^Sch6Hours^,^Sch7Hours^,^Sch8Hours^,^Sch9Hours^,^Sch10Hours^,^Sch11Hours^,^Sch12Hours^,^Sch13Hours^,^Sch14Hours^,^Sch15Hours^); 
SchM = new Array(^Sch0Mins^,^Sch1Mins^,^Sch2Mins^,^Sch3Mins^,^Sch4Mins^,^Sch5Mins^,^Sch6Mins^,^Sch7Mins^,^Sch8Mins^,^Sch9Mins^,^Sch10Mins^,^Sch11Mins^,^Sch12Mins^,^Sch13Mins^,^Sch14Mins^,^Sch15Mins^); 
SchB1 = new Array(^Sch0CfgB1^,^Sch1CfgB1^,^Sch2CfgB1^,^Sch3CfgB1^,^Sch4CfgB1^,^Sch5CfgB1^,^Sch6CfgB1^,^Sch7CfgB1^,^Sch8CfgB1^,^Sch9CfgB1^,^Sch10CfgB1^,^Sch11CfgB1^,^Sch12CfgB1^,^Sch13CfgB1^,^Sch14CfgB1^,^Sch15CfgB1^); 
SchB2 = new Array(^Sch0CfgB2^,^Sch1CfgB2^,^Sch2CfgB2^,^Sch3CfgB2^,^Sch4CfgB2^,^Sch5CfgB2^,^Sch6CfgB2^,^Sch7CfgB2^,^Sch8CfgB2^,^Sch9CfgB2^,^Sch10CfgB2^,^Sch11CfgB2^,^Sch12CfgB2^,^Sch13CfgB2^,^Sch14CfgB2^,^Sch15CfgB2^); 
SchB3 = new Array(^Sch0CfgB3^,^Sch1CfgB3^,^Sch2CfgB3^,^Sch3CfgB3^,^Sch4CfgB3^,^Sch5CfgB3^,^Sch6CfgB3^,^Sch7CfgB3^,^Sch8CfgB3^,^Sch9CfgB3^,^Sch10CfgB3^,^Sch11CfgB3^,^Sch12CfgB3^,^Sch13CfgB3^,^Sch14CfgB3^,^Sch15CfgB3^); 
SchB4 = new Array(^Sch0CfgB4^,^Sch1CfgB4^,^Sch2CfgB4^,^Sch3CfgB4^,^Sch4CfgB4^,^Sch5CfgB4^,^Sch6CfgB4^,^Sch7CfgB4^,^Sch8CfgB4^,^Sch9CfgB4^,^Sch10CfgB4^,^Sch11CfgB4^,^Sch12CfgB4^,^Sch13CfgB4^,^Sch14CfgB4^,^Sch15CfgB4^); 

// End
